name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ankitghosh1809
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push snake SVG to output branch
        run: |
          cd dist
          git init
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add -A
          git commit -m "chore: regenerate snake animation"
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ankitghosh1809/ankitghosh1809.git HEAD:output
